/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.9.0
 * Wed, 19 Feb 2025 09:29:45 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = new Map();
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function getElement(id, isParent=false) {
        let elem;
        if (Array.isArray(id) && id[0] === 'CONTAINER') {
            if (appInstance !== null) {
                elem = appInstance.container;
            } else if (typeof _initGlob !== 'undefined') {
                // if we are on the initialization stage, we still can have access
                // to the container element
                const contId = _initGlob.container;
                elem = isParent ? parent.document.getElementById(contId)
                        : document.getElementById(contId);
            }
        } else if (Array.isArray(id) && id[0] === 'WINDOW') {
            elem = isParent ? parent : window;
        } else if (Array.isArray(id) && id[0] === 'DOCUMENT') {
            elem = isParent ? parent.document : document;
        } else if (Array.isArray(id) && id[0] === 'BODY') {
            elem = isParent ? parent.document.body : document.body;
        } else if (Array.isArray(id) && id[0] === 'QUERYSELECTOR') {
            elem = isParent ? parent.document.querySelector(id)
                    : document.querySelector(id);
        } else {
            elem = isParent ? parent.document.getElementById(id)
                    : document.getElementById(id);
        }
        return elem;
    }
        
    function getElements(ids, isParent=false) {
        const elems = [];
        if (Array.isArray(ids) && ids[0] !== 'CONTAINER' && ids[0] !== 'WINDOW'
                && ids[0] !== 'DOCUMENT' && ids[0] !== 'BODY'
                && ids[0] !== 'QUERYSELECTOR') {
            for (let i = 0; i < ids.length; i++) {
                elems.push(getElement(ids[i], isParent));
            }
        } else {
            elems.push(getElement(ids, isParent));
        }
        return elems;
    }
        
    function isObjectWorthProcessing(obj) {
        return obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable)
            objFound = _pGlob.objCache.get(objName);
    
        if (objFound && objFound.name === objName)
            return objFound;
    
        function findValidByName(obj, objName) {
            if (obj.name === objName && isObjectWorthProcessing(obj))
                return obj;
    
            for (let i = 0; i < obj.children.length; i++) {
                const child = obj.children[i];
                const object = findValidByName(child, objName);
                if (object !== null)
                    return object;
            }
    
            return null;
        }
    
        if (appInstance.scene) {
            objFound = findValidByName(appInstance.scene, objName);
            if (objFound && pGlobAvailable)
                _pGlob.objCache.set(objName, objFound);
        }
    
        return objFound;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }
        
    function transformCoordsSpace(coords, spaceFrom, spaceTo, noSignChange=false) {
    
        if (spaceFrom === spaceTo) {
            return coords;
        }
    
        const y = coords.y;
        const z = coords.z;
    
        if (spaceFrom === 'Z_UP_RIGHT' && spaceTo === 'Y_UP_RIGHT') {
            coords.y = z;
            coords.z = noSignChange ? y : -y;
        } else if (spaceFrom === 'Y_UP_RIGHT' && spaceTo === 'Z_UP_RIGHT') {
            coords.y = noSignChange ? z : -z;
            coords.z = y;
        } else {
            console.error('transformCoordsSpace: Unsupported coordinate space');
        }
    
        return coords;
    }
        
    function getSceneCoordSystem() {
        const scene = appInstance.scene;
        if (scene && 'coordSystem' in scene.userData) {
            return scene.userData.coordSystem;
        }
    
        return 'Y_UP_RIGHT';
    }
        
    const transformEulerV3dToBlenderShortest = function() {
        const eulerTmp = new v3d.Euler();
        const eulerTmp2 = new v3d.Euler();
        const vec3Tmp = new v3d.Vector3();
    
        return function(euler, dest) {
            const eulerBlender = eulerTmp.copy(euler).reorder('YZX');
            const eulerBlenderAlt = eulerTmp2.copy(eulerBlender).makeAlternative();
    
            const len = vec3Tmp.setFromEuler(eulerBlender).lengthSq();
            const lenAlt = vec3Tmp.setFromEuler(eulerBlenderAlt).lengthSq();
    
            dest.copy(len < lenAlt ? eulerBlender : eulerBlenderAlt);
            return transformCoordsSpace(dest, 'Y_UP_RIGHT', 'Z_UP_RIGHT');
        }
    }();
        
    function RotationInterface() {
        /**
         * @ignore
         * For user manipulations use XYZ extrinsic rotations (which
         * are the same as ZYX intrinsic rotations)
         *     - Blender/Max/Maya use extrinsic rotations in the UI
         *     - XYZ is the default option, but could be set from
         *       some order hint if exported
         */
        this._userRotation = new v3d.Euler(0, 0, 0, 'ZYX');
        this._actualRotation = new v3d.Euler();
    }
    
    Object.assign(RotationInterface, {
        initObject: function(obj) {
            if (obj.userData.puzzles === undefined) {
                obj.userData.puzzles = {}
            }
            if (obj.userData.puzzles.rotationInterface === undefined) {
                obj.userData.puzzles.rotationInterface = new RotationInterface();
            }
    
            const rotUI = obj.userData.puzzles.rotationInterface;
            rotUI.updateFromObject(obj);
            return rotUI;
        },
    });
    
    Object.assign(RotationInterface.prototype, {
        updateFromObject: function(obj) {
            const SYNC_ROT_EPS = 1e-8;
    
            if (!this._actualRotation.equalsEps(obj.rotation, SYNC_ROT_EPS)) {
                this._actualRotation.copy(obj.rotation);
                this._updateUserRotFromActualRot();
            }
        },
    
        getActualRotation: function(euler) {
            return euler.copy(this._actualRotation);
        },
    
        setUserRotation: function(euler) {
            // don't copy the order, since it's fixed to ZYX for now
            this._userRotation.set(euler.x, euler.y, euler.z);
            this._updateActualRotFromUserRot();
        },
    
        getUserRotation: function(euler) {
            return euler.copy(this._userRotation);
        },
    
        _updateUserRotFromActualRot: function() {
            const order = this._userRotation.order;
            this._userRotation.copy(this._actualRotation).reorder(order);
        },
    
        _updateActualRotFromUserRot: function() {
            const order = this._actualRotation.order;
            this._actualRotation.copy(this._userRotation).reorder(order);
        },
    });
        
    function xrTraverseNonControllers(obj, callback) {
        if (obj.name.startsWith('XR_CONTROLLER_')) {
            return;
        }
    
        callback(obj);
    
        const children = obj.children;
        for (let i = 0, l = children.length; i < l; i++) {
            xrTraverseNonControllers(children[i], callback);
        }
    };
        
    function xrGetIntersections(controller) {
        controller.updateWorldMatrix(true, false);
    
        _pGlob.mat4Tmp.identity().extractRotation(controller.matrixWorld);
    
        const objList = [];
        xrTraverseNonControllers(appInstance.scene, obj => objList.push(obj));
    
        const raycaster = new v3d.Raycaster();
        raycaster.ray.origin.setFromMatrixPosition(controller.matrixWorld);
        raycaster.ray.direction.set(0, 0, -1).applyMatrix4(_pGlob.mat4Tmp);
    
        return raycaster.intersectObjects(objList, false);
    }
        
    function getObjectName(obj) {
        // auto-generated from a multi-material object, use parent name instead
        if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
            return obj.parent.name;
        } else {
            return obj.name;
        }
    }
        
    function isObjectAmongObjects(objNameToCheck, objNames) {
        if (!objNameToCheck) {
            return false;
        }
    
        for (let i = 0; i < objNames.length; i++) {
            if (objNameToCheck === objNames[i]) {
                return true;
            } else {
                // also check children which are auto-generated for multi-material objects
                const obj = getObjectByName(objNames[i]);
                if (obj && obj.type === 'Group') {
                    for (let j = 0; j < obj.children.length; j++) {
                        if (objNameToCheck === obj.children[j].name) {
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
        
    function xrOnSelect(event) {
        if (!_pGlob.objClickInfo) {
            return;
        }
    
        const controller = event.target;
        const intersections = xrGetIntersections(controller);
    
        if (intersections.length > 0) {
            const intersection = intersections[0];
            const obj = intersection.object;
    
            // save the object for the pickedObject block
            _pGlob.pickedObject = getObjectName(obj);
    
            _pGlob.objClickInfo.forEach(el => {
                const isPicked = obj && isObjectAmongObjects(getObjectName(obj),
                        retrieveObjectNames(el.objSelector));
                el.callbacks[isPicked ? 0 : 1]();
            });
        } else {
            // missed
            _pGlob.objClickInfo.forEach(el => el.callbacks[1]());
        }
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function unbindListener(target, type, listener, optionsOrUseCapture) {
        const index = _pGlob.eventListeners.findIndex(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                elem.optionsOrUseCapture, target, type, listener,
                optionsOrUseCapture);
        });
    
        if (index !== -1) {
            target.removeEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.splice(index, 1);
        }
    }
        
    const LIST_NONE = '<none>';
        
    function getEventOffsetCoords(event, touchId, dest) {
        if (event instanceof MouseEvent) {
            dest.set(event.offsetX, event.offsetY);
        } else if (window.TouchEvent && event instanceof TouchEvent) {
            const rect = event.target.getBoundingClientRect();
            let touches = event.touches;
            if (event.type === 'touchstart' || event.type === 'touchend'
                    || event.type === 'touchmove') {
                touches = event.changedTouches;
            }
    
            let touch = touches[0];
            for (let i = 0; i < touches.length; i++) {
                if (touches[i].identifier === touchId) {
                    touch = touches[i];
                    break;
                }
            }
    
            dest.set(touch.clientX - rect.left, touch.clientY - rect.top);
        }
        return dest;
    }
        
    function isChangedTouchOrNotTouchEventAtAll(event, touchId) {
        if (window.TouchEvent && event instanceof TouchEvent) {
            if (event.type === 'touchstart' || event.type === 'touchend'
                    || event.type === 'touchmove') {
                let isChanged = false;
                for (let i = 0; i < event.changedTouches.length; i++) {
                    if (event.changedTouches[i].identifier === touchId) {
                        isChanged = true;
                        break;
                    }
                }
                return isChanged;
            }
        }
    
        return true;
    }
        
    function getEventFirstTouchId(event) {
        if (window.TouchEvent && event instanceof TouchEvent) {
            if (event.type === 'touchstart' || event.type === 'touchend'
                    || event.type === 'touchmove') {
                return event.changedTouches[0].identifier;
            } else {
                return event.touches[0].identifier;
            }
        }
        return -1;
    }
        
    function createDragOverInfo() {
        return {
            draggedObjName: '',
            downX: 0, downY: 0,
            prevX: 0, prevY: 0,
            currX: 0, currY: 0,
            isDowned: false,
            isMoved: false,
            touchId: -1,
            downPointWorld: new v3d.Vector3(),
        };
    }
        
    function initObjectPicking(callback, eventType, mouseDownUseTouchStart=false,
            allowedMouseButtons=null) {
    
        const elem = appInstance.renderer.domElement;
        bindListener(elem, eventType, pickListener);
    
        if (eventType === 'mousedown') {
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, pickListener);
    
        } else if (eventType === 'dblclick') {
    
            let prevTapTime = 0;
    
            function doubleTapCallback(event) {
                const now = new Date().getTime();
                const timesince = now - prevTapTime;
    
                if (timesince < 600 && timesince > 0) {
                    pickListener(event);
                    prevTapTime = 0;
                    return;
                }
    
                prevTapTime = new Date().getTime();
            }
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, doubleTapCallback);
        }
    
        const raycaster = new v3d.Raycaster();
    
        function pickListener(event) {
    
            // to handle unload in loadScene puzzle
            if (!appInstance.getCamera()) {
                return;
            }
    
            event.preventDefault();
    
            let xNorm = 0;
            let yNorm = 0;
            if (event instanceof MouseEvent) {
                if (allowedMouseButtons !== null && allowedMouseButtons.indexOf(event.button) === -1) {
                    return;
                }
                xNorm = event.offsetX / elem.clientWidth;
                yNorm = event.offsetY / elem.clientHeight;
            } else if (event instanceof TouchEvent) {
                const rect = elem.getBoundingClientRect();
                xNorm = (event.changedTouches[0].clientX - rect.left) / rect.width;
                yNorm = (event.changedTouches[0].clientY - rect.top) / rect.height;
            }
    
            _pGlob.screenCoords.x = xNorm * 2 - 1;
            _pGlob.screenCoords.y = -yNorm * 2 + 1;
            raycaster.setFromCamera(_pGlob.screenCoords, appInstance.getCamera(true));
    
            const objList = [];
            appInstance.scene.traverse(obj => objList.push(obj));
    
            const intersects = raycaster.intersectObjects(objList, false);
            callback(intersects, event);
        }
    }
        
    function getSceneAnimFrameRate(scene) {
        if (scene && 'animFrameRate' in scene.userData) {
            return scene.userData.animFrameRate;
        }
        return 24;
    }
        
    function getSceneByAction(action) {
        const root = action.getRoot();
        let scene = root.type === 'Scene' ? root : null;
        root.traverseAncestors(ancObj => {
            if (ancObj.type === 'Scene') {
                scene = ancObj;
            }
        });
        return scene;
    }
        
    class AudioWebAudio {
        constructor() {
            this.audio = new v3d.Audio(new v3d.AudioListener());
    
            this._muted = false;
            this._volume = 1;
        }
    
        load(url) {
            const scope = this;
    
            const xhr = new XMLHttpRequest();
            xhr.open('GET', url);
            xhr.responseType = 'arraybuffer';
    
            xhr.onload = function(e) {
                if (this.status === 200) {
                    // new promise-based syntax is not currently supported in Safari
                    scope.audio.context.decodeAudioData(this.response, function(decodedData) {
                        scope.audio.setBuffer(decodedData);
                    });
                }
            }
    
            xhr.send();
            return this;
        }
    
        play() {
            if (this.audio.buffer === null) return;
            this.audio.play();
        }
    
        pause() {
            this.audio.pause();
        }
    
        stop() {
            if (this.audio.buffer === null || this.audio.source === null) return;
            this.audio.stop();
        }
    
        rewind() {
            if (this.audio.buffer === null || this.audio.source === null) return;
    
            const isPlaying = this.audio.isPlaying;
            this.audio.stop();
            if (isPlaying) {
                this.audio.play();
            }
        }
    
        setPlaybackTime(time) {
            // TODO: not easy with WebAudio
        }
    
        getPlaybackTime() {
            // TODO: not easy with WebAudio
            return 0;
        }
    
        getDuration() {
            return (this.audio.buffer === null) ? 0 : this.audio.buffer.duration;
        }
    
        setPlaybackRate(rate) {
            this.audio.setPlaybackRate(rate);
        }
    
        isPlaying() {
            return this.audio.isPlaying;
        }
    
        setLoop(looped) {
            this.audio.setLoop(looped);
        }
    
        setVolume(volume) {
            this._volume = volume;
            if (!this._muted) {
                this.audio.setVolume(volume);
            }
        }
    
        setMuted(muted) {
            this._muted = muted;
            this.audio.setVolume(muted ? 0 : this._volume);
        }
    
        toPositional() {
            if (!(this.audio instanceof v3d.PositionalAudio)) {
                const posAudio = new v3d.PositionalAudio(this.audio.listener);
                posAudio.fromAudio(this.audio);
                this.audio = posAudio;
            }
            return this.audio;
        }
    }

    return {
        getElement, getElements, getObjectByName, retrieveObjectNames,
        transformCoordsSpace, getSceneCoordSystem, transformEulerV3dToBlenderShortest, RotationInterface,
        xrOnSelect, bindListener, unbindListener, LIST_NONE,
        getEventOffsetCoords, isChangedTouchOrNotTouchEventAtAll, getEventFirstTouchId, getObjectName,
        createDragOverInfo, initObjectPicking, isObjectAmongObjects, getSceneAnimFrameRate,
        getSceneByAction, AudioWebAudio,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    // initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = true;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = true;
_initGlob.output.initOptions.useFullscreen = false;

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["show warning"] = show_warning;

var mode, id;

// createCSSRule puzzle
function createCSSRule(cssRule, cssRuleCont, isParent, mediaRule) {
    var style = document.createElement('style');
    style.type = 'text/css';
    if (mediaRule) {
        style.innerHTML = `@media ${mediaRule} { ${cssRule} { ${cssRuleCont} } }`;
    } else {
        style.innerHTML = `${cssRule} { ${cssRuleCont} }`;
    }

    var styles = (isParent) ? parent.document.getElementsByTagName('head')[0] :
                              document.getElementsByTagName('head')[0];
    styles.appendChild(style)
}

// addHTMLElement puzzle
function addHTMLElement(elemType, id, mode, targetId, isParent) {
    const win = isParent ? window.parent : window;

    const elem = win.document.createElement(elemType);
    if (id !== '')
        elem.id = id;

    const targetElem = PzLib.getElement(targetId, isParent);
    if (targetElem instanceof win.Element) {
        switch (mode) {
            case 'TO':
                targetElem.appendChild(elem);
                break;
            case 'BEFORE':
                targetElem.insertAdjacentElement('beforebegin', elem);
                break;
            case 'AFTER':
                targetElem.insertAdjacentElement('afterend', elem);
                break;
        }

        _pGlob.htmlElements.add(elem);
    }
}

// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if ((attr == 'href' || attr == 'src') && value instanceof Promise) {
            // resolve promise value for url-based attributes
            value.then(function(response) {
                elem[attr] = response;
            });
        } else {
            elem[attr] = value;
        }
    }
}

// show and hide puzzles
function changeVis(objSelector, bool) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        obj.visible = bool;
        obj.resolveMultiMaterial().forEach(function(objR) {
            objR.visible = bool;
        });
    }
}

// arHitPoint puzzle
function arHitPoint(coord) {

    if (!_pGlob.arHitPoint) {
        if (coord == 'xyz')
            return [0, 0, 0];
        else
            return 0;
    }

    var hitPoint = PzLib.transformCoordsSpace(_pGlob.vec3Tmp.copy(_pGlob.arHitPoint),
            'Y_UP_RIGHT', PzLib.getSceneCoordSystem());

    if (coord == 'xyz')
        return hitPoint.toArray();
    else
        return hitPoint[coord];
}

// setObjTransform puzzle
function setObjTransform(objSelector, isWorldSpace, mode, vector, offset){
    var x = vector[0];
      var y = vector[1];
      var z = vector[2];

    var objNames = PzLib.retrieveObjectNames(objSelector);

    function setObjProp(obj, prop, val) {
        if (!offset) {
            obj[mode][prop] = val;
        } else {
            if (mode != "scale")
                obj[mode][prop] += val;
            else
                obj[mode][prop] *= val;
        }
    }

    var inputsUsed = _pGlob.vec3Tmp.set(Number(x !== ''), Number(y !== ''),
            Number(z !== ''));
    var coords = _pGlob.vec3Tmp2.set(x || 0, y || 0, z || 0);

    if (mode === 'rotation') {
        // rotations are specified in degrees
        coords.multiplyScalar(v3d.MathUtils.DEG2RAD);
    }

    var coordSystem = PzLib.getSceneCoordSystem();

    PzLib.transformCoordsSpace(inputsUsed, coordSystem, 'Y_UP_RIGHT', true);
    PzLib.transformCoordsSpace(coords, coordSystem, 'Y_UP_RIGHT', mode === 'scale');

    for (var i = 0; i < objNames.length; i++) {

        var objName = objNames[i];
        if (!objName) continue;

        var obj = PzLib.getObjectByName(objName);
        if (!obj) continue;

        if (isWorldSpace && obj.parent) {
            obj.matrixWorld.decomposeE(obj.position, obj.rotation, obj.scale);

            if (inputsUsed.x) setObjProp(obj, "x", coords.x);
            if (inputsUsed.y) setObjProp(obj, "y", coords.y);
            if (inputsUsed.z) setObjProp(obj, "z", coords.z);

            obj.matrixWorld.composeE(obj.position, obj.rotation, obj.scale);
            obj.matrix.multiplyMatrices(_pGlob.mat4Tmp.copy(obj.parent.matrixWorld).invert(), obj.matrixWorld);
            obj.matrix.decompose(obj.position, obj.quaternion, obj.scale);

        } else if (mode === 'rotation' && coordSystem == 'Z_UP_RIGHT') {
            // Blender/Max coordinates

            // need all the rotations for order conversions, especially if some
            // inputs are not specified
            var euler = PzLib.transformEulerV3dToBlenderShortest(obj.rotation,
                    _pGlob.eulerTmp);
            PzLib.transformCoordsSpace(euler, coordSystem, 'Y_UP_RIGHT');

            if (inputsUsed.x) euler.x = offset ? euler.x + coords.x : coords.x;
            if (inputsUsed.y) euler.y = offset ? euler.y + coords.y : coords.y;
            if (inputsUsed.z) euler.z = offset ? euler.z + coords.z : coords.z;

            /**
             * convert from Blender/Max default XYZ extrinsic order to v3d XYZ
             * intrinsic with reversion (XYZ -> ZYX) and axes swizzling (ZYX -> YZX)
             */
            euler.order = "YZX";
            euler.reorder(obj.rotation.order);
            obj.rotation.copy(euler);

        } else if (mode === 'rotation' && coordSystem == 'Y_UP_RIGHT') {
            // Maya coordinates

            // Use separate rotation interface to fix ambiguous rotations for Maya,
            // might as well do the same for Blender/Max.

            var rotUI = PzLib.RotationInterface.initObject(obj);
            var euler = rotUI.getUserRotation(_pGlob.eulerTmp);
            // TODO(ivan): this probably needs some reasonable wrapping
            if (inputsUsed.x) euler.x = offset ? euler.x + coords.x : coords.x;
            if (inputsUsed.y) euler.y = offset ? euler.y + coords.y : coords.y;
            if (inputsUsed.z) euler.z = offset ? euler.z + coords.z : coords.z;

            rotUI.setUserRotation(euler);
            rotUI.getActualRotation(obj.rotation);
        } else {
            if (inputsUsed.x) setObjProp(obj, "x", coords.x);
            if (inputsUsed.y) setObjProp(obj, "y", coords.y);
            if (inputsUsed.z) setObjProp(obj, "z", coords.z);

        }

        obj.updateWorldMatrix(false, true);
    }

}

// arHitTest puzzle
_pGlob.arHitPoint = new v3d.Vector3(0, 0, 0);
_pGlob.arHitNormal = new v3d.Vector3(0, 0, 0);

function arHitTest(cbHit, cbMiss, smooth) {
    appInstance.renderer.xr.arHitTest(0, 0, function(point, normal) {

        smooth = v3d.MathUtils.clamp(smooth, 0, 1);

        var x = point.x;
        var y = point.y;
        var z = point.z;

        _pGlob.arHitPoint.x = _pGlob.arHitPoint.x * smooth + (1 - smooth) * x;
        _pGlob.arHitPoint.y = _pGlob.arHitPoint.y * smooth + (1 - smooth) * y;
        _pGlob.arHitPoint.z = _pGlob.arHitPoint.z * smooth + (1 - smooth) * z;

        _pGlob.arHitNormal.lerpVectors(normal, _pGlob.arHitNormal, smooth);

        cbHit();
    }, cbMiss);
}

// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}

// createVector puzzle
function createVector(x, y, z) {
    return [x, y, z];
};

// getObjTransform puzzle
function getObjTransform(objName, isWorldSpace, mode, coord) {
    if (!objName)
        return;
    var obj = PzLib.getObjectByName(objName);
    if (!obj)
        return;

    var coordSystem = PzLib.getSceneCoordSystem();

    var transformVal;

    if (isWorldSpace && obj.parent) {
        if (mode === 'position') {
            transformVal = PzLib.transformCoordsSpace(
                    obj.getWorldPosition(_pGlob.vec3Tmp), 'Y_UP_RIGHT',
                    coordSystem, mode === 'scale');
        } else if (mode === 'rotation') {
            transformVal = PzLib.transformCoordsSpace(
                    obj.getWorldEuler(_pGlob.eulerTmp, 'XYZ'), 'Y_UP_RIGHT',
                    coordSystem, mode === 'scale');
        } else if (mode === 'scale') {
            transformVal = PzLib.transformCoordsSpace(
                    obj.getWorldScale(_pGlob.vec3Tmp), 'Y_UP_RIGHT',
                    coordSystem, mode === 'scale');
        }

    } else if (mode === 'rotation' && coordSystem == 'Z_UP_RIGHT') {
        transformVal = PzLib.transformEulerV3dToBlenderShortest(obj.rotation,
                _pGlob.eulerTmp);

    } else if (mode === 'rotation' && coordSystem == 'Y_UP_RIGHT') {
        // Maya coordinates
        // Use separate rotation interface to fix ambiguous rotations for Maya,
        // might as well do the same for Blender/Max.

        var rotUI = PzLib.RotationInterface.initObject(obj);
        transformVal = rotUI.getUserRotation(_pGlob.eulerTmp);

    } else {
        transformVal = PzLib.transformCoordsSpace(obj[mode].clone(),
                'Y_UP_RIGHT', coordSystem, mode === 'scale');
    }

    if (mode === 'rotation') {
        transformVal.x = v3d.MathUtils.radToDeg(transformVal.x);
        transformVal.y = v3d.MathUtils.radToDeg(transformVal.y);
        transformVal.z = v3d.MathUtils.radToDeg(transformVal.z);
    }

    if (coord == 'xyz') {
        // remove order component for Euler vectors
        return transformVal.toArray().slice(0, 3);
    } else {
        return transformVal[coord];
    }
}

// setObjDirection puzzle
function setObjDirection(objSelector, vector, isPoint, lockUp) {
    var objNames = PzLib.retrieveObjectNames(objSelector);
    var x = vector[0] || 0;
      var y = vector[1] || 0;
      var z = vector[2] || 0;

    var coords = PzLib.transformCoordsSpace(_pGlob.vec3Tmp.set(x, y, z),
            PzLib.getSceneCoordSystem(), 'Y_UP_RIGHT');

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        if (!objName) continue;

        var obj = PzLib.getObjectByName(objName);
        if (!obj) continue;

        if (!isPoint) {
            coords.normalize().add(obj.position);
        }

        if (lockUp) {
            // NOTE: partially copy-pasted from LockedTrackConstraint

            var targetWorldPos = new v3d.Vector3(coords.x, coords.y, coords.z);

            var lockDir = new v3d.Vector3(0, 1, 0);

            if (obj.isCamera || obj.isLight)
                var trackDir = new v3d.Vector3(0, 0, -1);
            else
                var trackDir = new v3d.Vector3(0, 0, 1);

            var projDir = new v3d.Vector3();
            var plane = _pGlob.planeTmp;

            var objWorldPos = new v3d.Vector3();
            objWorldPos.setFromMatrixPosition(obj.matrixWorld);

            plane.setFromNormalAndCoplanarPoint(lockDir, objWorldPos);
            plane.projectPoint(targetWorldPos, projDir).sub(objWorldPos);

            var sign = _pGlob.vec3Tmp2.crossVectors(trackDir, projDir).dot(lockDir) > 0 ? 1 : -1;

            obj.setRotationFromAxisAngle(plane.normal, sign * trackDir.angleTo(projDir));

            if (obj.parent) {
                obj.parent.matrixWorld.decompose(_pGlob.vec3Tmp2, _pGlob.quatTmp, _pGlob.vec3Tmp2);
                obj.quaternion.premultiply(_pGlob.quatTmp.invert());
            }

        } else {

            obj.lookAt(coords.x, coords.y, coords.z);

        }

        obj.updateWorldMatrix(false, true);
    }
}

// updateTextObject puzzle
function updateTextObj(objSelector, text) {
    const objNames = PzLib.retrieveObjectNames(objSelector);

    for (let i = 0; i < objNames.length; i++) {
        const objName = objNames[i];
        if (!objName) continue;
        const obj = PzLib.getObjectByName(objName);
        if (!obj || !obj.geometry || !obj.geometry.cloneWithText)
            continue;
        const textGeom = obj.geometry;
        obj.geometry = textGeom.cloneWithText(String(text));
        textGeom.dispose();
    }
}

// enterARMode puzzle
function enterARMode(refSpace, allowHTML, enterCb, exitCb, unAvailableCb) {

    switch (refSpace) {
        case 'SITTING':
            var referenceSpace = 'local-floor';
            break;
        case 'WALKING':
            var referenceSpace = 'unbounded';
            break;
        case 'ORIGIN':
            var referenceSpace = 'local';
            break;
        case 'ROOM':
            var referenceSpace = 'bounded-floor';
            break;
        case 'VIEWER':
            var referenceSpace = 'viewer';
            break;
        default:
            console.error('puzzles: Wrong VR reference space');
            return;
    }


    appInstance.initWebXR('immersive-ar', referenceSpace, function() {

        var controllers = appInstance.xrControllers;

        for (var i = 0; i < controllers.length; i++) {
            var controller = controllers[i];

            PzLib.bindListener(controller, 'select', PzLib.xrOnSelect);

            _pGlob.xrSessionCallbacks.forEach(function(pair) {
                PzLib.bindListener(controller, pair[0], pair[1]);
            });
        }

        _pGlob.xrSessionAcquired = true;

        enterCb();

    }, unAvailableCb, function() {

        var controllers = appInstance.xrControllers;

        for (var i = 0; i < controllers.length; i++) {
            var controller = controllers[i];

            PzLib.unbindListener(controller, 'select', PzLib.xrOnSelect);

            _pGlob.xrSessionCallbacks.forEach(function(pair) {
                PzLib.unbindListener(controller, pair[0], pair[1]);
            });
        }

        _pGlob.xrSessionAcquired = false;

        // to cleanup supplementary XR_CAMERA_CONTROL_OBJECT
        _pGlob.objCache.clear();

        exitCb();

    }, { domOverlay: allowHTML });
}

// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;

        PzLib.bindListener(elem, eventType, callback);
    }
}

// exportToUSDZ puzzle
function exportToUSDZ(objSelector) {
    let obj;

    if (objSelector === '' || objSelector === PzLib.LIST_NONE)
        obj = appInstance.scene;
    else
        obj = PzLib.getObjectByName(objSelector);

    if (!obj)
        return;

    // COMPAT: iOS < 14
    if (Blob.prototype.arrayBuffer == undefined)
        Blob.prototype.arrayBuffer = function() {
            return new Response(this).arrayBuffer()
        }

    const usdzExporter = new v3d.USDZExporter();

    return new Promise(function(resolve, reject) {

        usdzExporter.parse(obj).then(function(value) {

            const dataUrl = URL.createObjectURL(new Blob([value], { type: 'application/octet-stream' }));
            resolve(dataUrl);

        }, function(reason) {

            console.error('exportToUSDZ: export failed: ' + reason);
            reject(reason);

        });

    });

}

// checkARMode puzzle
function checkARMode(availableCb, usdzCb, unAvailableCb) {
    v3d.Detector.checkWebXR('immersive-ar', availableCb, function() {
        let usdzSupported = false;

        // NOTE: WebView in iOS reports as unsupported, use whitelist
        if (v3d.Detector.checkIOS() && window.webkit && window.webkit.messageHandlers) {
            if (/CriOS|EdgiOS|FxiOS|GSA|DuckDuckGo/.test(navigator.userAgent))
                usdzSupported = true;
        } else {
            const a = document.createElement('a');
            if (a.relList.supports('ar'))
                usdzSupported = true;
        }

        if (usdzSupported)
            usdzCb();
        else
            unAvailableCb();
    });
}

const intersectPlaneCSS = (() => {
    const coords = new v3d.Vector2();
    const rc = new v3d.Raycaster(); // always check visibility

    return (plane, cssX, cssY, dest) => {
        coords.x = (cssX / appInstance.getWidth()) * 2 - 1;
        coords.y = - (cssY / appInstance.getHeight()) * 2 + 1;
        rc.setFromCamera(coords, appInstance.getCamera(true));
        return rc.ray.intersectPlane(plane, dest);
    };
})();

// dragMoveAdv puzzle
const dragMoveAdv = (() => {
    _pGlob.dragMoveOrigins = _pGlob.dragMoveOrigins || {};

    // Blender/Max right-handed -> Verge3D right-handed
    const Z_UP_RIGHT_COORDS = Object.freeze({
        X: _pGlob.AXIS_X,
        Y: _pGlob.AXIS_Z,
        Z: _pGlob.AXIS_Y,
    });

    // Blender/Max right-handed -> Verge3D right-handed with a camera parent
    const Z_UP_RIGHT_CAM_COORDS = Object.freeze({
        X: _pGlob.AXIS_X,
        Y: _pGlob.AXIS_Y,
        Z: _pGlob.AXIS_Z,
    });

    // Maya right-handed -> Verge3D right-handed
    const Y_UP_RIGHT_COORDS = Object.freeze({
        X: _pGlob.AXIS_X,
        Y: _pGlob.AXIS_Y,
        Z: _pGlob.AXIS_Z,
    });

    const draggedObjPosWorld = new v3d.Vector3();
    const dragAxisWorld = new v3d.Vector3(); // only for the X, Y and Z modes
    const dragPlaneNorWorld = new v3d.Vector3();
    const dragPlane = new v3d.Plane();
    const intersectPoint0 = new v3d.Vector3();
    const intersectPoint1 = new v3d.Vector3();
    const dragDelta = new v3d.Vector3();
    const parentMatWorldInv = new v3d.Matrix3();

    return (objSelector, mode, spaceType, blockId, parentDragOverBlockId) => {
        const camera = appInstance.getCamera();
        if (!camera) return;

        if (!_pGlob.objDragOverInfoByBlock) return;

        const objNames = PzLib.retrieveObjectNames(objSelector);

        const info = _pGlob.objDragOverInfoByBlock[parentDragOverBlockId];
        if (!info) return;

        const draggedObj = PzLib.getObjectByName(info.draggedObjName);
        if (!draggedObj) return;

        if (!(blockId in _pGlob.dragMoveOrigins)) {
            _pGlob.dragMoveOrigins[blockId] = [];
        }
        const posOrigins = _pGlob.dragMoveOrigins[blockId];
        const lenDiff = objNames.length - posOrigins.length;
        for (let i = 0; i < lenDiff; i++) {
            posOrigins.push(new v3d.Vector3());
        }

        for (let i = 0; i < objNames.length; i++) {
            const obj = PzLib.getObjectByName(objNames[i]);
            if (!obj) continue;

            const posOrigin = posOrigins[i];
            if (!info.isMoved) {
                // the object position before the first move is used as an initial value
                posOrigin.copy(obj.position);
            }

            const isZupRight = PzLib.getSceneCoordSystem() === 'Z_UP_RIGHT';
            const needParentCamCoords = obj.parent && obj.parent.isCamera
                    && spaceType === 'PARENT';
            const coords = isZupRight
                    ? (needParentCamCoords ? Z_UP_RIGHT_CAM_COORDS : Z_UP_RIGHT_COORDS)
                    : Y_UP_RIGHT_COORDS;

            const isMode1d = mode === 'X' || mode === 'Y' || mode === 'Z';
            const isMode2d = mode === 'XY' || mode === 'XZ' || mode === 'YZ';
            const isMode3d = mode === 'XYZ';

            // determining the normal for the drag plane to raycast against
            if (isMode1d) {

                dragAxisWorld.copy(coords[mode]);

                if (spaceType === 'LOCAL') {
                    dragAxisWorld.transformDirection(obj.matrixWorld);
                } else if (spaceType === 'PARENT') {
                    dragAxisWorld.transformDirection(obj.parent.matrixWorld);
                } else {
                    // considered to be in the world space, no need for transforming
                }

                camera.getWorldDirection(dragPlaneNorWorld);
                dragPlaneNorWorld.cross(dragAxisWorld).cross(dragAxisWorld);

            } else if (isMode2d) {

                const modeNormal = mode === 'XY' ? 'Z' : (mode === 'XZ' ? 'Y' : 'X');
                dragPlaneNorWorld.copy(coords[modeNormal]);

                if (spaceType === 'LOCAL') {
                    dragPlaneNorWorld.transformDirection(obj.matrixWorld);
                } else if (spaceType === 'PARENT') {
                    dragPlaneNorWorld.transformDirection(obj.parent.matrixWorld);
                } else {
                    // considered to be in the world space, no need for transforming
                }

            } else {

                camera.getWorldDirection(dragPlaneNorWorld);

            }

            draggedObj.getWorldPosition(draggedObjPosWorld);
            dragPlane.setFromNormalAndCoplanarPoint(dragPlaneNorWorld, draggedObjPosWorld);

            const res0 = intersectPlaneCSS(dragPlane, info.downX, info.downY,
                    intersectPoint0);
            const res1 = intersectPlaneCSS(dragPlane, info.currX, info.currY,
                    intersectPoint1);

            if (res0 !== null && res1 !== null) {
                dragDelta.subVectors(intersectPoint1, intersectPoint0);
                if (isMode1d) {
                    dragDelta.projectOnVector(dragAxisWorld);
                }

                parentMatWorldInv.setFromMatrix4(obj.parent.matrixWorld).invert();
                dragDelta.applyMatrix3(parentMatWorldInv);
                obj.position.addVectors(posOrigin, dragDelta);
            }

            obj.updateWorldMatrix(false, true);
        }
    };
})();

// whenDraggedOver puzzle
_pGlob.objDragOverInfoGlobal = [];
_pGlob.objDragOverInfoByBlock = {}

PzLib.initObjectPicking(function(intersects, downEvent) {

    _pGlob.objDragOverInfoGlobal.forEach(function(el) {

        if (downEvent instanceof MouseEvent)
            if (el.mouseButtons.indexOf(downEvent.button) == -1)
                return;

        var maxIntersects = el.xRay ? intersects.length : Math.min(1, intersects.length);

        for (var i = 0; i < maxIntersects; i++) {
            var obj = intersects[i].object;
            var objName = PzLib.getObjectName(obj);

            if (PzLib.isObjectAmongObjects(objName, [el.objName])) {
                el.callback({
                    downEvent: downEvent,
                    draggedObjName: objName,
                    downPointWorld: intersects[i].point,
                });
            }

        }

    });

}, 'mousedown', true);

// whenDraggedOver puzzle
function registerOnDrag(objSelector, xRay, mouseButtons, cbStart, cbMove, cbDrop, blockId) {

    var cb = function(cbParam) {

        if (appInstance.controls) {
            appInstance.controls.enabled = false;
        }

        if (!(blockId in _pGlob.objDragOverInfoByBlock)) {
            _pGlob.objDragOverInfoByBlock[blockId] = PzLib.createDragOverInfo();
        }
        var info = _pGlob.objDragOverInfoByBlock[blockId];

        // NOTE: don't use more than one pointing event, e.g. don't process
        // some events related to multitouch actions
        if (info.isDowned) {
            return;
        }

        var touchId = PzLib.getEventFirstTouchId(cbParam.downEvent);
        var coords = PzLib.getEventOffsetCoords(cbParam.downEvent, touchId,
                _pGlob.vec2Tmp);

        info.downX = info.prevX = info.currX = coords.x;
        info.downY = info.prevY = info.currY = coords.y;
        info.touchId = touchId;
        info.isDowned = true;
        info.isMoved = false;
        info.draggedObjName = cbParam.draggedObjName;
        info.downPointWorld.copy(cbParam.downPointWorld);

        cbStart(cbParam.downEvent);

        var elem = appInstance.container;

        var moveCb = function(e) {
            if (!PzLib.isChangedTouchOrNotTouchEventAtAll(e, info.touchId)) {
                // don't handle events not intended for this particular touch
                return;
            }

            var coords = PzLib.getEventOffsetCoords(e, info.touchId, _pGlob.vec2Tmp);
            info.prevX = info.currX;
            info.prevY = info.currY;
            info.currX = coords.x;
            info.currY = coords.y;
            cbMove(e);
            info.isMoved = true;
        }
        var upCb = function(e) {
            if (!PzLib.isChangedTouchOrNotTouchEventAtAll(e, info.touchId)) {
                // don't handle events not intended for this particular touch
                return;
            }

            var coords = PzLib.getEventOffsetCoords(e, info.touchId, _pGlob.vec2Tmp);
            info.currX = coords.x;
            info.currY = coords.y;
            info.prevX = info.currX;
            info.prevY = info.currY;
            cbDrop(e);
            info.isDowned = false;

            PzLib.unbindListener(elem, 'mousemove', moveCb);
            PzLib.unbindListener(elem, 'touchmove', moveCb);
            PzLib.unbindListener(elem, 'mouseup', upCb);
            PzLib.unbindListener(elem, 'touchend', upCb);
            if (appInstance.controls) {
                appInstance.controls.enabled = true;
            }
        }

        PzLib.bindListener(elem, 'mousemove', moveCb);
        PzLib.bindListener(elem, 'touchmove', moveCb);
        PzLib.bindListener(elem, 'mouseup', upCb);
        PzLib.bindListener(elem, 'touchend', upCb);
    }

    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        _pGlob.objDragOverInfoGlobal.push({
            objName: objName,
            callback: cb,
            xRay: xRay,
            mouseButtons: mouseButtons
        });
    }
}

// dragRotateAdv puzzle
const dragRotateAdv = (() => {

    // Blender/Max right-handed -> Verge3D right-handed
    const Z_UP_RIGHT_COORDS = Object.freeze({
        X: _pGlob.AXIS_X,
        Y: _pGlob.AXIS_Z,
        Z: _pGlob.AXIS_Y,
    });

    // Blender/Max right-handed -> Verge3D right-handed with a camera parent
    const Z_UP_RIGHT_CAM_COORDS = Object.freeze({
        X: _pGlob.AXIS_X,
        Y: _pGlob.AXIS_Y,
        Z: _pGlob.AXIS_Z,
    });

    // Maya right-handed -> Verge3D right-handed
    const Y_UP_RIGHT_COORDS = Object.freeze({
        X: _pGlob.AXIS_X,
        Y: _pGlob.AXIS_Y,
        Z: _pGlob.AXIS_Z,
    });

    const axisVec = new v3d.Vector3();
    const axisVecLocal = new v3d.Vector3();

    const objQuatWorld = new v3d.Quaternion();
    const objQuatWorldConj = new v3d.Quaternion();
    const parentQuatWorld = new v3d.Quaternion();

    const objPosWorld = new v3d.Vector3();
    const axisLineEndPoint = new v3d.Vector3();
    const axisLine = new v3d.Line3();
    const downPointProjOnLine = new v3d.Vector3();

    const rotationPoint = new v3d.Vector3();
    const vecPointerFrom = new v3d.Vector2();
    const vecPointerTo = new v3d.Vector2();

    const viewVec = new v3d.Vector3();

    const rotationQuat = new v3d.Quaternion();

    return (objSelector, mode, spaceType, blockId, parentDragOverBlockId) => {

        const camera = appInstance.getCamera(true);
        if (!camera) return;

        if (!_pGlob.objDragOverInfoByBlock) return;
        const info = _pGlob.objDragOverInfoByBlock[parentDragOverBlockId];
        if (!info) return;

        const appWidth = appInstance.getWidth();
        const appHeight = appInstance.getHeight();

        const isZupRight = PzLib.getSceneCoordSystem() === 'Z_UP_RIGHT';

        const objNames = PzLib.retrieveObjectNames(objSelector);

        for (let i = 0; i < objNames.length; i++) {
            const obj = PzLib.getObjectByName(objNames[i]);
            if (!obj) continue;

            obj.getWorldQuaternion(objQuatWorld);

            const needParentCamCoords = obj.parent && obj.parent.isCamera
                    && spaceType === 'PARENT';
            const coords = isZupRight
                    ? (needParentCamCoords ? Z_UP_RIGHT_CAM_COORDS : Z_UP_RIGHT_COORDS)
                    : Y_UP_RIGHT_COORDS;
            axisVec.copy(coords[mode]);
            if (spaceType === 'LOCAL') {
                axisVec.applyQuaternion(objQuatWorld);
            } else if (spaceType === 'PARENT') {
                obj.parent.getWorldQuaternion(parentQuatWorld);
                axisVec.applyQuaternion(parentQuatWorld);
            } else {
                // considered to be in the world space, no need for transforming
            }

            obj.getWorldPosition(objPosWorld);

            axisLineEndPoint.addVectors(objPosWorld, axisVec);
            axisLine.set(objPosWorld, axisLineEndPoint);
            axisLine.closestPointToPoint(info.downPointWorld, false, downPointProjOnLine);

            rotationPoint.copy(downPointProjOnLine);
            rotationPoint.project(camera);

            const rotX = (rotationPoint.x + 1) / 2 * appWidth;
            const rotY = (-rotationPoint.y + 1) / 2 * appHeight;

            vecPointerFrom.set(info.prevX - rotX, info.prevY - rotY);
            vecPointerTo.set(info.currX - rotX, info.currY - rotY);

            objQuatWorldConj.copy(objQuatWorld).conjugate();
            axisVecLocal.copy(axisVec).applyQuaternion(objQuatWorldConj).normalize();

            /**
             * Negated in order to keep the rotation direction consistent with
             * mouse movement after transforming coordinates from the NDC space
             * to the canvas space.
             */
            let rotAngle = -(vecPointerTo.angle() - vecPointerFrom.angle());

            /**
             * Negated if the rotation axis points outwards the camera. Not
             * needed and can have issues for objects parented to camera.
             */
            if (!needParentCamCoords) {
                camera.getWorldDirection(viewVec);
                if (viewVec.dot(axisVec) > 0) {
                    rotAngle = -rotAngle;
                }
            }

            rotationQuat.setFromAxisAngle(axisVecLocal, rotAngle);

            obj.quaternion.multiply(rotationQuat);
            obj.updateWorldMatrix(false, true);
        }
    };
})();

// dragScale puzzle
_pGlob.dragScaleOrigins = {};

function dragScale(objSelector, mode, blockId, parentDragOverBlockId) {
    const camera = appInstance.getCamera(true);
    if (!camera)
        return;

    if (!_pGlob.objDragOverInfoByBlock)
        return;

    const objNames = PzLib.retrieveObjectNames(objSelector);

    const info = _pGlob.objDragOverInfoByBlock[parentDragOverBlockId];
    if (!info) return;

    if (!(blockId in _pGlob.dragScaleOrigins)) {
        _pGlob.dragScaleOrigins[blockId] = [];
    }
    const scaleOrigins = _pGlob.dragScaleOrigins[blockId];
    let lenDiff = objNames.length - scaleOrigins.length;
    for (let i = 0; i < lenDiff; i++) {
        scaleOrigins.push(new v3d.Vector3());
    }

    const coordSystem = PzLib.getSceneCoordSystem();

    for (let i = 0; i < objNames.length; i++) {
        const obj = PzLib.getObjectByName(objNames[i]);

        if (!obj) {
            continue;
        }

        const scaleOrigin = scaleOrigins[i];

        if (!info.isMoved) {
            // the object scale before the first move is used as an initial value
            scaleOrigin.copy(obj.scale);
        }

        const objPos = obj.getWorldPosition(_pGlob.vec3Tmp);
        objPos.project(camera);

        let objX = (objPos.x + 1) / 2 * appInstance.getWidth();
        let objY = (-objPos.y + 1) / 2 * appInstance.getHeight();

        const vecFrom = _pGlob.vec2Tmp.set(info.downX - objX, objY - info.downY);
        const vecTo = _pGlob.vec2Tmp2.set(info.currX - objX, objY - info.currY);

        if (mode == "X" || mode == "Y" || mode == "Z") {
            let coord;
            if (coordSystem == 'Z_UP_RIGHT')
                coord = mode == "X" ? "x" : (mode == "Y" ? "z" : "y");
            else
                coord = mode == "X" ? "x" : (mode == "Y" ? "y" : "z");

            obj.scale[coord] = Math.max(scaleOrigin[coord]
                    * vecTo.dot(vecFrom) / vecFrom.lengthSq(), _pGlob.MIN_DRAG_SCALE);
            obj.updateWorldMatrix(false, true);

        }  else if (mode == 'XYZ') {
            const minVecDragScale = _pGlob.vec3Tmp2.setScalar(_pGlob.MIN_DRAG_SCALE);
            let scaleFactor = vecTo.dot(vecFrom) / vecFrom.lengthSq();
            obj.scale.copy(scaleOrigin).multiplyScalar(scaleFactor).max(minVecDragScale);
            obj.updateWorldMatrix(false, true);
        }
    }
}

// toFixedPoint puzzle
function toFixedPoint(num, prec) {
    prec = Math.pow(10, prec);
    return Math.round(num * prec)/prec;
}

// setTimeout puzzle
function registerSetTimeout(timeout, callback) {
    window.setTimeout(callback, 1000 * timeout);
}

// whenClicked puzzle
function registerOnClick(objSelector, xRay, doubleClick, mouseButtons, cbDo, cbIfMissedDo) {

    // for AR/VR
    _pGlob.objClickInfo = _pGlob.objClickInfo || [];

    _pGlob.objClickInfo.push({
        objSelector: objSelector,
        callbacks: [cbDo, cbIfMissedDo]
    });

    PzLib.initObjectPicking(function(intersects, event) {

        var isPicked = false;

        var maxIntersects = xRay ? intersects.length : Math.min(1, intersects.length);

        for (var i = 0; i < maxIntersects; i++) {
            var obj = intersects[i].object;
            var objName = PzLib.getObjectName(obj);
            var objNames = PzLib.retrieveObjectNames(objSelector);

            if (PzLib.isObjectAmongObjects(objName, objNames)) {
                // save the object for the pickedObject block
                _pGlob.pickedObject = objName;
                isPicked = true;
                cbDo(event);
            }
        }

        if (!isPicked) {
            _pGlob.pickedObject = '';
            cbIfMissedDo(event);
        }

    }, doubleClick ? 'dblclick' : 'mousedown', false, mouseButtons);
}

// Procedure for showing AR warnings
function show_warning(id) {
  setHTMLElemStyle('display', 'block', 'warning_center', false);
  setHTMLElemStyle('display', 'block', id, false);
  registerSetTimeout(3, function() {
    setHTMLElemStyle('display', 'none', 'warning_center', false);
    setHTMLElemStyle('display', 'none', id, false);
  });
}

_pGlob.animMixerCallbacks = [];

var initAnimationMixer = function() {

    function onMixerFinished(e) {
        var cb = _pGlob.animMixerCallbacks;
        var found = [];
        for (var i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (var i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished)) {
            PzLib.bindListener(appInstance.mixer, 'finished', onMixerFinished);
        }
    };

}();

// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;
        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();
                if (loop && (loop != "AUTO"))
                    action.loop = v3d[loop];
                var scene = PzLib.getSceneByAction(action);
                var frameRate = PzLib.getSceneAnimFrameRate(scene);

                action.repetitions = Infinity;

                var timeScale = Math.abs(parseFloat(speed));
                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                var callbacks = _pGlob.animMixerCallbacks;
                var found = false;

                for (var j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            var callbacks = _pGlob.animMixerCallbacks;
            for (var j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            var scene = PzLib.getSceneByAction(action);
            var frameRate = PzLib.getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        case 'SET_SPEED':
            var timeScale = parseFloat(speed);
            action.timeScale = rev ? -timeScale : timeScale;
            break;
        }
    }

    for (var i = 0; i < animations.length; i++) {
        var animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}

// loadMedia puzzle
function loadMedia_WebAudio(url) {
    if (!v3d.Detector.checkWebAudio()) {
        if (!_pGlob.noWebAudioReported) {
            _pGlob.noWebAudioReported = true;
            console.warn('puzzles: Web Audio API not supported');
        }
        return null;
    }

    var elems = _pGlob.mediaElements;
    if (!(url in elems)) {
        elems[url] = new PzLib.AudioWebAudio().load(url);
    }
    return elems[url];
}

// volume puzzle
function volume(mediaElem, volume) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);

    volume = Number(volume);
    if (Number.isNaN(volume)) {
        return;
    }

    mediaElems.forEach(mediaElem => {
        mediaElem.setVolume(v3d.MathUtils.clamp(volume, 0.0, 1.0));
    });
}

// playSound puzzle
function playSound(mediaElem, loop) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);
    mediaElems.forEach(mediaElem => {
        mediaElem.setLoop(loop);
        if (mediaElem.audio)
            mediaElem.audio.context.resume();
        mediaElem.play();
    });
}


createCSSRule('.enter-AR-button', "position: absolute; display: block; z-index: 1; background-color: rgba(255, 255, 255, 0); width: 200px; height: 50px; bottom: 20px; left: 50%; margin-left: -100px; background-size: 100%; cursor: pointer; outline: 0;", false, '');
addHTMLElement('a', 'enter_AR_button', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'enter-AR-button', 'enter_AR_button', false);
addHTMLElement('img', 'enter_AR_img', 'TO', 'enter_AR_button', false);
setHTMLElemAttribute('src', 'media/enter_AR_button.png', 'enter_AR_img', false);
createCSSRule('.warning-center', "position: absolute; width: 100%; height: 50px; top: 50%; margin-top: -25px; left: 0px; display: block;", false, '');
createCSSRule('.warning-AR-unavailable', "position: absolute; width: 242px; height: 50px; left: 50%; margin-left: -121px; display: none;", false, '');
createCSSRule('.warning-could-not-enter-AR', "position: absolute; width: 362px; height: 50px; display: none; z-index: 1; left: 50%; margin-left: -181px;", false, '');
addHTMLElement('div', 'warning_center', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'warning-center', 'warning_center', false);
addHTMLElement('div', 'warning_AR_unavailable', 'TO', 'warning_center', false);
setHTMLElemAttribute('className', 'warning-AR-unavailable', 'warning_AR_unavailable', false);
addHTMLElement('img', 'warning_AR_unavailable_img', 'TO', 'warning_AR_unavailable', false);
setHTMLElemAttribute('src', 'media/warning_AR_unavailable.png', 'warning_AR_unavailable_img', false);
addHTMLElement('div', 'warning_could_not_enter_AR', 'TO', 'warning_center', false);
setHTMLElemAttribute('className', 'warning-could-not-enter-AR', 'warning_could_not_enter_AR', false);
createCSSRule('.info-button', "position: absolute; width: 50px; height: 50px; z-index: 1; top: 10px; right: 10px; background-repeat: no-repeat; display: block; overflow: hidden; border-style: none; border-color: #000000; cursor: pointer;", false, '');
addHTMLElement('a', 'info_button', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'info-button', 'info_button', false);
setHTMLElemAttribute('href', 'https://www.soft8soft.com/augmented-reality-in-the-browser/', 'info_button', false);
addHTMLElement('img', 'info_button_img', 'TO', 'info_button', false);
setHTMLElemAttribute('src', 'media/info.png', 'info_button_img', false);

mode = 'indicator';

// Check AR capabilities
checkARMode(function() {
  // Enter AR!
  eventHTMLElem('pointerup', 'enter_AR_button', false, function(event) {
    enterARMode('ORIGIN', true, function() {
      changeVis(['GROUP', 'farmer_group'], false);
      changeVis('prompt_move_around', true);
      arHitTest(function() {
        if (mode == 'indicator') {
          changeVis(['GROUP', 'indicator_group'], true);
          setObjTransform('indicator_invis_plane', false, 'position', [arHitPoint('x'), arHitPoint('y'), arHitPoint('z')], false);
        }
        changeVis('prompt_move_around', false);
      }, function() {
        changeVis(['GROUP', 'indicator_group'], false);
      }, 0.7);
      // Hide Enter AR button
      setHTMLElemStyle('display', 'none', 'enter_AR_button', false);
      changeVis('edit_button', true);
      changeVis(['drag_move', 'drag_rotate', 'drag_scale', 'ready_button'], false);
    }, function() {
      changeVis(['GROUP', 'farmer_group'], true);
      changeVis('prompt_move_around', false);
      setObjTransform('farmer_armature', false, 'position', createVector(0, 0, 0), false);
      // Look at me!
      setObjDirection('farmer_armature', getObjTransform('Camera', false, 'position', 'xyz'), true, true);
      // Hide Enter AR button
      setHTMLElemStyle('display', 'block', 'enter_AR_button', false);
      changeVis(['edit_button', 'ready_button', 'drag_move', 'drag_rotate', 'drag_scale', 'scale_percentage'], false);
      setObjTransform('farmer_armature', false, 'scale', [1, 1, 1], false);
      updateTextObj('scale_percentage', '100%');
    }, function() {
      show_warning('warning_could_not_enter_AR');
    });
  });
}, function() {
  setHTMLElemAttribute('href', exportToUSDZ('farmer_mesh'), 'enter_AR_button', false);
  setHTMLElemAttribute('rel', 'ar', 'enter_AR_button', false);
  setHTMLElemAttribute('download', 'farmer.usdz', 'enter_AR_button', false);
}, function() {
  // Enter AR!
  eventHTMLElem('pointerup', 'enter_AR_button', false, function(event) {
    show_warning('warning_AR_unavailable');
  });
});

registerOnDrag('drag_move', false, [0,1,2], function() {}, function() {
  dragMoveAdv('farmer_armature', 'XY', 'WORLD', '8o8nOyTtkWq?W_SQs-|_', 'G1ye9@dbVWAx+dC?wdwk');
}, function() {}, 'G1ye9@dbVWAx+dC?wdwk');

registerOnDrag('drag_rotate', false, [0,1,2], function() {}, function() {
  dragRotateAdv('farmer_armature', 'Z', 'WORLD', ';V@_mj~C6#6st}%|L2fM', 'zs{d~:/oJ6OM9r)o6R,C');
}, function() {}, 'zs{d~:/oJ6OM9r)o6R,C');

registerOnDrag('drag_scale', false, [0,1,2], function() {}, function() {
  dragScale('farmer_armature', 'Z', '!m;X%nzGL9gqF6*2@x_7', 'WLYxwe*;^db}c?brtmU5');
  dragScale('farmer_armature', 'X', '7Ila8yLKn=*PF~GVAC5?', 'WLYxwe*;^db}c?brtmU5');
  dragScale('farmer_armature', 'Y', 'b;DQ|a30Sv-+Lq$dcj.H', 'WLYxwe*;^db}c?brtmU5');
  updateTextObj('scale_percentage', String(Math.round(toFixedPoint(getObjTransform('farmer_armature', false, 'scale', 'z'), 2) * 100)) + '%');
}, function() {}, 'WLYxwe*;^db}c?brtmU5');

registerOnClick('ready_button', false, false, [0,1,2], function() {
  registerSetTimeout(0.1, function() {
    changeVis(['drag_move', 'drag_rotate', 'drag_scale', 'ready_button', 'scale_percentage'], false);
    changeVis('edit_button', true);
    changeVis(['GROUP', 'indicator_group'], true);
    mode = 'indicator';
  });
}, function() {});
registerOnClick('edit_button', false, false, [0,1,2], function() {
  registerSetTimeout(0.1, function() {
    changeVis(['drag_move', 'drag_rotate', 'drag_scale', 'ready_button', 'scale_percentage'], true);
    changeVis('edit_button', false);
    changeVis(['GROUP', 'indicator_group'], false);
    mode = 'edit';
  });
}, function() {});

// Position the character
registerOnClick('indicator_invis_plane', false, false, [0,1,2], function() {
  changeVis(['GROUP', 'farmer_group'], true);
  changeVis(['drag_move', 'drag_rotate', 'drag_scale', 'scale_percentage', 'ready_button'], false);
  setObjTransform('farmer_armature', false, 'position', [arHitPoint('x'), arHitPoint('y'), arHitPoint('z')], false);
  // Look at me!
  setObjDirection('farmer_armature', getObjTransform('Camera', false, 'position', 'xyz'), true, true);
}, function() {});

// Setup the character
changeVis(['GROUP', 'farmer_group'], true);

changeVis(['GROUP', 'indicator_group'], false);
changeVis(['drag_move', 'drag_rotate', 'drag_scale', 'scale_percentage', 'ready_button'], false);

operateAnimation('PLAY', 'farmer_armature', 1, 100, 'LoopRepeat', 1,
        function() {}, false);

    volume(loadMedia_WebAudio('sounds/saying_hello.mp3'), 0.6);
registerOnClick('farmer_mesh', false, false, [0,1,2], function() {
  playSound(loadMedia_WebAudio('sounds/saying_hello.mp3'), false);

  operateAnimation('STOP', 'farmer_armature', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('PLAY', 'farmer_armature', 101, 140, 'LoopOnce', 1,
          function() {

    operateAnimation('PLAY', 'farmer_armature', 1, 100, 'LoopRepeat', 1,
            function() {}, false);

        }, false);

      }, function() {});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
